const GROKBOT_PARTS=[['hands','双手','⌁'],['feet','双脚','⌄'],['tail','尾巴','〜'],['antenna','天线','⌃']];
const GROKBOT_ACCESSORIES=[['straw-hat','草帽','◒'],['glasses','眼镜','◎'],['bowtie','蝴蝶结','⋈'],['cape','披风','◢']];
const selectedParts=new Set(),selectedAccessories=new Set(),partRoot=document.querySelector('#part-options'),accessoryRoot=document.querySelector('#accessory-options'),quickClasses=['quick-bounce','quick-shake','quick-peek','quick-pinch','quick-squish','quick-wave'];let quickTimer=0,lastQuickAction={key:'none',name:'无'};
function prepareBot(){
  document.querySelector('#accessory-briefs')?.remove();document.querySelector('#rainbow-rings')?.remove();document.querySelectorAll('.rainbow-orbit,.body-depth,#accessory-magic-hat').forEach(node=>node.remove());
  const straw=document.querySelector('#accessory-hat');straw.id='accessory-straw-hat';straw.innerHTML='<path d="M63 28Q72-24 114-28Q156-24 165 28Z"/><ellipse cx="114" cy="31" rx="91" ry="18"/><path class="hat-band" d="M64 10Q114 22 164 10L166 27Q114 38 62 27Z"/>';
}
prepareBot();
function prepareControlPanel(){const panel=document.createElement('div');panel.className='control-panel';panel.setAttribute('aria-label','GrokBot 配置面板');viewer.after(panel);let node=panel.nextElementSibling;while(node&&node.tagName!=='FOOTER'){const next=node.nextElementSibling;panel.appendChild(node);node=next}}
prepareControlPanel();
function selectionText(items,selected,empty){return selected.size?items.filter(item=>selected.has(item[0])).map(item=>item[1]).join('、'):empty}
function updateSummaries(){document.querySelector('#part-summary').textContent=selectionText(GROKBOT_PARTS,selectedParts,'默认无部件');document.querySelector('#accessory-summary').textContent=selectionText(GROKBOT_ACCESSORIES,selectedAccessories,'默认无配饰')}
function setSelection(kind,id,enabled){const selected=kind==='part'?selectedParts:selectedAccessories;if(enabled)selected.add(id);else selected.delete(id);document.querySelector(`#${kind}-${id}`)?.classList.toggle('enabled',enabled);document.querySelector(`[data-${kind}="${id}"]`)?.setAttribute('aria-pressed',String(enabled));updateSummaries()}
function renderToggles(items,selected,root,prefix){items.forEach(item=>{const button=document.createElement('button');button.type='button';button.dataset[prefix]=item[0];button.setAttribute('aria-pressed','false');button.innerHTML=`<b>${item[2]}</b><span>${item[1]}</span>`;button.addEventListener('click',()=>setSelection(prefix,item[0],!selected.has(item[0])));root.appendChild(button)})}
renderToggles(GROKBOT_PARTS,selectedParts,partRoot,'part');renderToggles(GROKBOT_ACCESSORIES,selectedAccessories,accessoryRoot,'accessory');
function playQuickAction(name){clearTimeout(quickTimer);[...quickClasses,'act-bounce','act-tilt','act-scan','act-turn','act-pulse','act-glitch'].forEach(cls=>bot.classList.remove(cls));viewer.classList.remove('guides');void bot.offsetWidth;bot.classList.add(`quick-${name}`);lastQuickAction={key:name,name:{bounce:'蹦跳',shake:'摇头',peek:'探头',pinch:'捏脸',squish:'挤压',wave:'挥手'}[name]};hint.textContent={bounce:'GrokBot 开心地跳了起来',shake:'GrokBot 正在疯狂摇头',peek:'GrokBot 偷偷探出头',pinch:'两边一捏，GrokBot 像果冻一样弹回来了',squish:'软乎乎地挤一下',wave:'GrokBot 向你挥了挥手'}[name];quickTimer=setTimeout(()=>{bot.classList.remove(`quick-${name}`);hint.textContent='在 GrokBot 区域滑动，控制它的视线'},name==='wave'?1350:name==='pinch'?1200:950)}
document.querySelector('#quick-actions').addEventListener('click',event=>{const button=event.target.closest('[data-quick-action]');if(button)playQuickAction(button.dataset.quickAction)});
function randomizeDecorations(){GROKBOT_PARTS.forEach(item=>setSelection('part',item[0],Math.random()<.42));GROKBOT_ACCESSORIES.forEach(item=>setSelection('accessory',item[0],false))}
function randomizeAll(){window.GrokbotCustomizer?.randomize();window.GrokbotCore?.randomize();randomizeDecorations();const actions=['bounce','shake','peek','pinch','squish','wave'];playQuickAction(actions[Math.floor(Math.random()*actions.length)]);return window.getGrokbotSnapshot()}
const customizedSnapshot=window.getGrokbotSnapshot;window.getGrokbotSnapshot=()=>({...customizedSnapshot(),parts:[...selectedParts],partNames:GROKBOT_PARTS.filter(item=>selectedParts.has(item[0])).map(item=>item[1]),accessories:[...selectedAccessories],accessoryNames:GROKBOT_ACCESSORIES.filter(item=>selectedAccessories.has(item[0])).map(item=>item[1]),quickAction:lastQuickAction.key,quickActionName:lastQuickAction.name});
window.GrokbotEnhancements={playQuickAction,randomizeDecorations,randomizeAll,quickActions:['bounce','shake','peek','pinch','squish','wave']};updateSummaries();
