const REPOSITORY_URL='https://github.com/zhulin025/LaoA-GrokBot';const shareSheet=document.querySelector('#share-sheet'),shareImage=document.querySelector('#share-image'),shareCaption=document.querySelector('#share-caption'),toast=document.querySelector('#toast'),bridgeHint=document.querySelector('#bridge-hint');let currentDataUrl='',currentCreation=null,toastTimer=0;
const INSPIRING=['生活就像骑自行车，要保持平衡就得不断前进。——爱因斯坦','世界上只有一种英雄主义，就是认清生活后依然热爱生活。——罗曼·罗兰','不要等待机会，而要创造机会。——萧伯纳','成功是从失败到失败，依然不改热情。——丘吉尔','每一个不曾起舞的日子，都是对生命的辜负。——尼采','不积跬步，无以至千里。——荀子'];
const FUNNY=['今天也要元气满满，哪怕元气只够打开外卖软件。','我不是拖延，我是在给灵感充分的助跑距离。','脑子说要努力，身体说这个提议改天再议。','生活给我关上一扇门，我熟练地打开了购物车。','人生没有过不去的坎，只有过不完的验证码。','如果生活没有惊喜，可能是快递还在路上。'];
function showToast(message){clearTimeout(toastTimer);toast.textContent=message;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),2400)}
function randomCopy(){const list=Math.random()<.5?INSPIRING:FUNNY;return list[Math.floor(Math.random()*list.length)]}
function composition(snapshot){const decorations=[...(snapshot.partNames||[]),...(snapshot.accessoryNames||[])];return `${snapshot.colorName}、${snapshot.shapeName}，表情 ${String(snapshot.expression).padStart(2,'0')}，状态${snapshot.stateName}，动作${snapshot.quickActionName}${decorations.length?'，搭配'+decorations.join('、'):''}。`}
function renderCreation(snapshot){const decorations=[...(snapshot.partNames||[]),...(snapshot.accessoryNames||[])];currentDataUrl=window.GrokbotShareRenderer.render(snapshot);shareImage.src=currentDataUrl;shareCaption.textContent=`${snapshot.colorName} · ${snapshot.shapeName} · ${snapshot.quickActionName}${decorations.length?' · '+decorations.join('、'):''}`}
function openSheet(){currentCreation={...window.getGrokbotSnapshot(),copy:randomCopy()};renderCreation(currentCreation);shareSheet.hidden=false;document.body.classList.add('sheet-open')}
function closeSheet(){shareSheet.hidden=true;document.body.classList.remove('sheet-open')}
function saveImage(){if(!currentDataUrl)return;const link=document.createElement('a');link.href=currentDataUrl;link.download='my-grokbot.png';document.body.appendChild(link);link.click();link.remove();showToast('图片已开始下载')}
function openXShare(text){const url=`https://x.com/intent/post?text=${encodeURIComponent(text)}&url=${encodeURIComponent(location.href)}`;window.open(url,'_blank','noopener,noreferrer')}
function shareSocial(){if(!currentCreation)return;const text=`我的 GrokBot：${composition(currentCreation)}\n${currentCreation.copy}\n项目仓库：${REPOSITORY_URL}\n#GrokBot`;openXShare(text);showToast('已打开 X 发布页；图片可先保存后添加')}
function randomizeBot(){try{window.GrokbotEnhancements.randomizeAll();showToast('已随机出一只新 GrokBot')}catch(error){showToast('随机失败，请刷新页面后重试')}}
document.querySelector('#randomize').addEventListener('click',randomizeBot);document.querySelector('#create-work').addEventListener('click',openSheet);document.querySelector('#close-sheet').addEventListener('click',closeSheet);document.querySelector('#sheet-backdrop').addEventListener('click',closeSheet);document.querySelector('#save-image').addEventListener('click',saveImage);document.querySelector('#share-social').addEventListener('click',shareSocial);
